version: "3.7"

services:
  modmailbot:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes: 
      - data:/usr/modmailbot/
    restart: unless-stopped
    environment:
      - MM_TOKEN=
      - MM_MAIN_SERVER_ID=
      - MM_INBOX_SERVER_ID=
      - MM_LOG_CHANNEL_ID=
      - MM_PREFIX=
      - MM_INBOX_SERVER_PERMISSION=
      - MM_STATUS=
      - MM_PORT=
      - MM_URL=http://127.0.0.1:PORT
      - MM_PLUGINS=./plugins/CloseAddons/index.js||./plugins/EmbedMessages/embedMessages.js||./plugins/Help/index.js||./plugins/HexedHelp/help.js||./plugins/LogSearch/logsearch.js||./plugins/MMEmergencyLink/emergencyLink.js||./plugins/modmailbot-formatter/index.js||./plugins/Ping/ping.js||./plugins/ReactionThreads/reactionThreads.js||./plugins/replyPrefix/replyPrefix.js
      - MM_REACTION_THREADS_OWNER_ID=
    ports:
      - ${MM_PORT:-8890}:${MM_PORT:-8890}

volumes:
  data: