version: "3.7"

services:
  modmailbot:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes: 
      - data:/usr/modmailbot/
    restart: unless-stopped
    env_file:
      - ./.env
    ports:
      - ${MM_PORT:-8890}:${MM_PORT:-8890}

volumes:
  data: